version: '3'
#
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_dash
    environment:
      TZ: "America/Mexico_City"
    ports:
      - "2021:2021"
    volumes:
      - ./app/assets:/code/assets
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: MP_Web
    environment:
      TZ: "America/Mexico_City"
    command: bash -c "gunicorn -w 4 -b :2021 app:server"
    volumes:
      - ./app:/code
    expose:
      - "2021"
    ports:
      - "8888:8888"

volumes:
  postgres_data:



